name       : arcanist
version    : 6
release    : 3
source     :
    - git|https://github.com/phacility/arcanist.git : 3b6b523c2b236e3724a1e115f126cb6fd05fa128
license    : Apache-2.0
component  : programming.tools
summary    : Command line interface for Phabricator
description: |
    Arcanist is the command-line tool for Phabricator. It allows you to interact with Phabricator installs to send code for review, download patches, transfer files, view status, make API calls, and various other things.
rundeps    :
    - libphutil
install    : |
    install -dm00644 $installdir/usr/bin/
    install -dm00644 $installdir/usr/share/php/arcanist/
    cp -R * $installdir/usr/share/php/arcanist/
    rm $installdir/usr/share/php/arcanist/{LICENSE,NOTICE,README.md}
    rm $installdir/usr/share/php/arcanist/bin/arc.bat
    ln -s /usr/share/php/arcanist/bin/arc $installdir/usr/bin/arc
    install -Dm00644 resources/shell/bash-completion $installdir/usr/share/bash-completion/completions/arc
    install -Dm00644 resources/shell/bash-completion $installdir/usr/share/zsh/site-functions/_arc
