name       : arcanist
version    : 2018.02.17
release    : 7
source     :
    - git|https://github.com/phacility/arcanist.git : be1dd7e2ba230d77f894637fdcbc7d5a47dc7082
license    : Apache-2.0
component  : programming.tools
summary    : Command line interface for Phabricator
description: |
    Arcanist is the command-line tool for Phabricator. It allows you to interact with Phabricator installs to send code for review, download patches, transfer files, view status, make API calls, and various other things.
rundeps    :
    - libphutil
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-Switch-branches-after-first-creating-them-for-Initia.patch
    %patch -p1 < $pkgfiles/0001-Remove-author-revision-prompt-since-our-use-of-Arcan.patch
install    : |
    install -dm00644 $installdir/usr/bin/
    install -dm00644 $installdir/usr/share/php/arcanist/
    cp -R * $installdir/usr/share/php/arcanist/
    rm $installdir/usr/share/php/arcanist/{LICENSE,NOTICE,README.md}
    rm $installdir/usr/share/php/arcanist/bin/arc.bat
    ln -s /usr/share/php/arcanist/bin/arc $installdir/usr/bin/arc
    install -Dm00644 resources/shell/bash-completion $installdir/usr/share/bash-completion/completions/arc
    install -Dm00644 resources/shell/bash-completion $installdir/usr/share/zsh/site-functions/_arc
